# Generated by Django 5.2.8 on 2025-11-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tech_stack', models.CharField(blank=True, max_length=200)),
                ('project_url', models.URLField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
